# Generated by Django 6.0.7 on 2026-07-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Nom Complet')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse E-mail')),
                ('role', models.CharField(choices=[('student', 'Étudiant IT'), ('developer', 'Développeur (Débutant/Confirmé)'), ('cloud_enthusiast', 'Passionné du Cloud'), ('other', 'Autre')], max_length=50, verbose_name='Profil')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'Inscription")),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
